from asyncio import AbstractEventLoop
from collections.abc import Awaitable, Callable

class IsolaError(Exception): ...
class InvalidArgumentError(IsolaError): ...
class InternalError(IsolaError): ...
class StreamFullError(IsolaError): ...
class StreamClosedError(IsolaError): ...

class _RunResultCore:
    @property
    def result_json(self) -> list[str]: ...
    @property
    def final_json(self) -> str | None: ...
    @property
    def stdout(self) -> list[str]: ...
    @property
    def stderr(self) -> list[str]: ...
    @property
    def logs(self) -> list[str]: ...
    @property
    def errors(self) -> list[str]: ...

class _StreamCore:
    def __init__(self, capacity: int = 1024) -> None: ...
    def push_json(self, json: str, blocking: bool = False) -> None: ...
    def push_json_async(self, json: str) -> Awaitable[None]: ...
    def end(self) -> None: ...

class _SandboxCore:
    def configure_json(self, config_json: str) -> None: ...
    def set_callback(
        self, callback: Callable[[str, str | None], None] | None
    ) -> None: ...
    def set_http_handler(
        self,
        callback: Callable[
            [str, str, dict[str, str], bytes | None],
            Awaitable[tuple[int, dict[str, str], str, object]],
        ]
        | None,
        event_loop: AbstractEventLoop | None,
    ) -> None: ...
    def start(self) -> Awaitable[None]: ...
    def load_script(self, code: str) -> Awaitable[None]: ...
    def run(
        self, func: str, args: list[tuple[str, str | None, object]] = ...
    ) -> Awaitable[_RunResultCore]: ...
    def close(self) -> None: ...

class _ContextCore:
    def __init__(self) -> None: ...
    def configure_json(self, config_json: str) -> None: ...
    def initialize_template(self, runtime_path: str) -> Awaitable[None]: ...
    def instantiate(self) -> Awaitable[_SandboxCore]: ...
    def close(self) -> None: ...
