package promptkit:python;

world python-executor {
    export %python-executor : interface {
        resource script {
            constructor();
            run: func(%script: string, %func: string, %args: list<string>) -> result<string, string>;
        }

        run-script: func(%script: string, %func: string, %args: list<string>) -> result<string, string>;
    }
}