package promptkit:python;

world python-vm {
    export %python-vm : interface {
        eval-script: func(%script: string) -> result<_, string>;
        call-func: func(%func: string, %args: list<string>) -> result<string, string>;
    }
}