/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const UiIndexLazyImport = createFileRoute('/ui/')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UiIndexLazyRoute = UiIndexLazyImport.update({
  path: '/ui/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/ui/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/ui/': {
      id: '/ui/'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof UiIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ IndexRoute, UiIndexLazyRoute })

/* prettier-ignore-end */


/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/ui/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/ui/": {
      "filePath": "ui/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */