#ifndef ISOLA_H_INCLUDED
#define ISOLA_H_INCLUDED

/* Don't modify this file manually. It is autogenerated by cbindgen. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum isola_error_code {
  ISOLA_ERROR_CODE_OK = 0,
  ISOLA_ERROR_CODE_INVALID_ARGUMENT = 1,
  ISOLA_ERROR_CODE_INTERNAL = 2,
  ISOLA_ERROR_CODE_STREAM_FULL = 3,
  ISOLA_ERROR_CODE_STREAM_CLOSED = 4,
} isola_error_code;

typedef enum isola_callback_event {
  ISOLA_CALLBACK_EVENT_RESULT_JSON = 0,
  ISOLA_CALLBACK_EVENT_END_JSON = 4,
  ISOLA_CALLBACK_EVENT_STDOUT = 1,
  ISOLA_CALLBACK_EVENT_STDERR = 2,
  ISOLA_CALLBACK_EVENT_ERROR = 3,
  ISOLA_CALLBACK_EVENT_LOG = 5,
} isola_callback_event;

typedef struct isola_context_handle isola_context_handle;

/**
 * Opaque handle for an in-flight hostcall response.
 *
 * The C side delivers the result by calling exactly one of:
 * - `isola_hostcall_response_resolve` — on success
 * - `isola_hostcall_response_reject` — on failure
 *
 * Either call consumes and frees the handle.
 */
typedef struct isola_hostcall_response isola_hostcall_response;

/**
 * Opaque handle for an in-flight HTTP response.
 *
 * The C side drives the response through three phases:
 * 1. `isola_http_response_body_start` — deliver status and headers
 * 2. `isola_http_response_body_push` — deliver body chunks (zero or more)
 * 3. `isola_http_response_body_close` — signal EOF and free the handle
 */
typedef struct isola_http_response_body isola_http_response_body;

typedef struct isola_sandbox_handle isola_sandbox_handle;

typedef struct isola_stream_handle isola_stream_handle;

/**
 * C-compatible HTTP header.
 */
typedef struct isola_http_header {
  const uint8_t *name;
  size_t name_len;
  const uint8_t *value;
  size_t value_len;
} isola_http_header;

/**
 * C-compatible HTTP request passed to the handler callback.
 *
 * All referenced request data is valid only for the duration of the callback.
 * Copy any values needed by asynchronous work.
 */
typedef struct isola_http_request {
  const char *method;
  const char *url;
  const struct isola_http_header *headers;
  size_t headers_len;
  const uint8_t *body;
  size_t body_len;
} isola_http_request;

/**
 * Unified vtable for sandbox event handling and optional HTTP support.
 *
 * - `on_event` is required.
 * - `http_request` is optional (NULL to disable HTTP).
 *
 * Callbacks may run on runtime worker threads. The callback functions and
 * `user_data` must remain valid until the sandbox is destroyed and must be
 * safe to access concurrently.
 */
typedef struct isola_sandbox_handler_vtable {
  /**
   * Called for output events (results, logs, stdout/stderr).
   *
   * `data` is valid only for the duration of the callback. It may be `NULL`
   * only when `len` is zero.
   */
  void (*on_event)(enum isola_callback_event, const uint8_t*, size_t, void*);
  /**
   * Called to initiate an HTTP request.
   *
   * The callback should return immediately. The `response_body` handle
   * is Rust-owned; the C side completes the response asynchronously:
   *
   * 1. `isola_http_response_body_start(response_body, status)` — once
   *    headers arrive.
   * 2. `isola_http_response_body_push(response_body, data, len)` — for each
   *    body chunk.
   * 3. `isola_http_response_body_close(response_body)` — to signal EOF and
   *    free the handle.
   */
  void (*http_request)(const struct isola_http_request *request,
                       struct isola_http_response_body *response_body,
                       void *user_data);
  /**
   * Called to handle a hostcall from guest code.
   *
   * The callback should return immediately. The `response` handle
   * is Rust-owned; the C side delivers the result asynchronously:
   *
   * - `isola_hostcall_response_resolve(response, data, len)` — on success
   * - `isola_hostcall_response_reject(response, error_message)` — on failure
   *
   * Exactly one of resolve/reject/cancel must be called. The call frees the
   * handle.
   */
  void (*hostcall)(const char *call_type,
                   const uint8_t *payload,
                   size_t payload_len,
                   struct isola_hostcall_response *response,
                   void *user_data);
} isola_sandbox_handler_vtable;

/**
 * Stable-width wire value describing an argument's storage kind.
 *
 * Additional values may be added in future releases. Unknown values are
 * rejected by the receiving runtime.
 */
typedef int32_t isola_argument_kind;

/**
 * Stable-width wire value describing the encoding of an argument.
 *
 * Additional values may be added in future releases. Unknown values are
 * rejected by the receiving runtime.
 */
typedef int32_t isola_argument_type;

typedef struct isola_blob {
  const uint8_t *data;
  size_t len;
} isola_blob;

typedef struct isola_encoded_value {
  isola_argument_type format;
  struct isola_blob data;
} isola_encoded_value;

typedef union isola_argument_value {
  struct isola_encoded_value value;
  const struct isola_stream_handle *stream;
} isola_argument_value;

typedef struct isola_argument {
  isola_argument_kind kind;
  const char *name;
  union isola_argument_value value;
} isola_argument;

#define ISOLA_ARGUMENT_TYPE_JSON 0

#define ISOLA_ARGUMENT_TYPE_CBOR 1

#define ISOLA_ARGUMENT_KIND_VALUE 0

#define ISOLA_ARGUMENT_KIND_STREAM 1

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Creates a new isola context with the specified number of threads.
 *
 * # Safety
 *
 * `out_context` must point to writable handle storage. It is set to `NULL`
 * before context creation, so it remains `NULL` if creation fails.
 */
enum isola_error_code isola_context_create(int nr_thread,
                                           struct isola_context_handle **out_context);

/**
 * Initializes the isola context with the specified path.
 *
 * # Safety
 *
 * `ctx` must be a live context handle and `path` must be a valid,
 * null-terminated C string. `NULL` arguments are rejected.
 */
enum isola_error_code isola_context_initialize(struct isola_context_handle *ctx, const char *path);

/**
 * Sets a configuration value for the isola context.
 *
 * Must be called **before** `isola_context_initialize`. Returns
 * `ISOLA_ERROR_CODE_INVALID_ARGUMENT` if the context is already initialized
 * or if `key` is unrecognized.
 *
 * # Supported keys
 *
 * | Key        | Value                                                | Default                         |
 * |------------|------------------------------------------------------|---------------------------------|
 * | `max_memory` | Decimal byte count (e.g. `"67108864"` for 64 MiB). | `67108864` (64 MiB)            |
 * | `prelude`  | Guest prelude source code. Empty string disables it. | `"import sandbox.asyncio"`      |
 * | `cache`    | Path to the compiled-component cache directory.      | `<wasm_dir>/cache`              |
 * | `env`      | JSON: `{"name":"VAR","value":"val"}`                 | *(none)*                        |
 * | `mount`    | JSON: `{"host":"/h","guest":"/g","writable":false}`  | *(none; `/lib` always mounted)* |
 *
 * The `env` and `mount` keys may be called multiple times to add multiple
 * entries. For `mount`, `writable` defaults to `false` when omitted.
 *
 * # Safety
 *
 * The caller must ensure that both `key` and `value` are valid,
 * null-terminated C strings.
 */
enum isola_error_code isola_context_config_set(struct isola_context_handle *ctx,
                                               const char *key,
                                               const char *value);

/**
 * Destroy a context handle. Passing `NULL` is allowed and has no effect.
 *
 * # Safety
 * A non-`NULL` handle must have been returned by `isola_context_create` and
 * must not have been destroyed previously.
 */
void isola_context_destroy(struct isola_context_handle *ctx);

/**
 * Creates a new sandbox instance from the context.
 *
 * # Safety
 *
 * `ctx` must be a live context handle and `out_sandbox` must point to writable
 * handle storage. The output is set to `NULL` before creation.
 */
enum isola_error_code isola_sandbox_create(const struct isola_context_handle *ctx,
                                           struct isola_sandbox_handle **out_sandbox);

/**
 * Destroy a sandbox handle. Passing `NULL` is allowed and has no effect.
 *
 * # Safety
 * A non-`NULL` handle must have been returned by `isola_sandbox_create` and
 * must not have been destroyed previously.
 */
void isola_sandbox_destroy(struct isola_sandbox_handle *sandbox);

/**
 * Sets a per-sandbox configuration value, overriding context-level defaults.
 *
 * Must be called **after** `isola_sandbox_create` and **before**
 * `isola_sandbox_start`. Returns `ISOLA_ERROR_CODE_INVALID_ARGUMENT` if the
 * sandbox has already been started or if `key` is unrecognized.
 *
 * # Supported keys
 *
 * | Key          | Value                                                | Default         |
 * |--------------|------------------------------------------------------|-----------------|
 * | `max_memory` | Decimal byte count (e.g. `"33554432"` for 32 MiB).  | *(from context)*|
 * | `env`        | JSON: `{"name":"VAR","value":"val"}`                 | *(none)*        |
 * | `mount`      | JSON: `{"host":"/h","guest":"/g","writable":false}`  | *(none)*        |
 *
 * The `env` and `mount` keys may be called multiple times. Per-sandbox
 * settings are merged with context-level defaults: `max_memory` replaces,
 * `env` overrides by key, and `mount` overrides by guest path.
 *
 * # Safety
 *
 * The caller must ensure that both `key` and `value` are valid,
 * null-terminated C strings.
 */
enum isola_error_code isola_sandbox_set_config(struct isola_sandbox_handle *sandbox,
                                               const char *key,
                                               const char *value);

/**
 * Sets the handler vtable on a sandbox.
 *
 * The vtable is copied; the caller may free it after this call returns.
 * Must be called exactly once, before `isola_sandbox_start`.
 *
 * # Safety
 *
 * `vtable` must point to a valid `SandboxHandlerVtable`.
 */
enum isola_error_code isola_sandbox_set_handler(struct isola_sandbox_handle *sandbox,
                                                const struct isola_sandbox_handler_vtable *vtable,
                                                void *user_data);

/**
 * Start a configured sandbox.
 *
 * # Safety
 * `sandbox` must be a live handle returned by `isola_sandbox_create`. `NULL`
 * is rejected.
 */
enum isola_error_code isola_sandbox_start(struct isola_sandbox_handle *sandbox);

/**
 * Loads a script into the sandbox.
 *
 * # Safety
 *
 * The caller must ensure that `input` is a valid, null-terminated C string.
 */
enum isola_error_code isola_sandbox_load_script(struct isola_sandbox_handle *sandbox,
                                                const char *input,
                                                uint64_t timeout_in_ms);

/**
 * Runs a function in the sandbox with the specified arguments.
 *
 * # Safety
 *
 * The caller must ensure that:
 * - `func` is a valid, null-terminated C string
 * - `args` is a valid pointer to an array of `Argument` structs of length
 *   `args_len`
 * - Each `Argument` in the array has valid pointers and data
 */
enum isola_error_code isola_sandbox_run(struct isola_sandbox_handle *sandbox,
                                        const char *func,
                                        const struct isola_argument *args,
                                        size_t args_len,
                                        uint64_t timeout_in_ms);

/**
 * Creates a new stream handle for streaming arguments.
 *
 * # Safety
 *
 * `out_stream` must point to writable handle storage. The output is set to
 * `NULL` before creation. Unknown `format` values are rejected.
 */
enum isola_error_code isola_stream_create(isola_argument_type format,
                                          struct isola_stream_handle **out_stream);

/**
 * Pushes data to a stream.
 *
 * # Safety
 *
 * The caller must ensure that `data` points to a valid buffer of length `len`.
 *
 * # Parameters
 *
 * * `blocking` - If non-zero, blocks until space is available in the channel.
 *   If zero, returns immediately with an error if the channel is full.
 */
enum isola_error_code isola_stream_push(const struct isola_stream_handle *stream,
                                        const uint8_t *data,
                                        size_t len,
                                        int blocking);

/**
 * Signals the end of a stream and frees the handle.
 *
 * After calling this function, no more data can be pushed to the stream
 * and the handle is invalid.
 *
 * # Safety
 * `stream` must be a live handle returned by `isola_stream_create` that has
 * not already been ended. `NULL` is rejected.
 */
enum isola_error_code isola_stream_end(struct isola_stream_handle *stream);

/**
 * Delivers the HTTP status code and response headers.
 *
 * Must be called exactly once per handle, before any
 * `isola_http_response_body_push` calls.
 *
 * The header data is copied; the caller may free the array after this
 * call returns.
 *
 * # Safety
 *
 * - `body` must be a live handle obtained from an `http_request` callback.
 * - `headers` must point to a valid array of `headers_len` elements (may be
 *   NULL if `headers_len` is 0).
 */
enum isola_error_code isola_http_response_body_start(const struct isola_http_response_body *body,
                                                     uint16_t status,
                                                     const struct isola_http_header *headers,
                                                     size_t headers_len);

/**
 * Pushes a chunk of response body data.
 *
 * May be called from any thread. Blocks if the internal channel is full.
 *
 * # Safety
 *
 * - `body` must be a live handle obtained from an `http_request` callback.
 * - `data` must point to a valid buffer of `len` bytes.
 */
enum isola_error_code isola_http_response_body_push(const struct isola_http_response_body *body,
                                                    const uint8_t *data,
                                                    size_t len);

/**
 * Signals EOF and frees the response body handle.
 *
 * Must be called exactly once per handle, even if no data was pushed.
 *
 * # Safety
 *
 * `body` must be `NULL` or a live handle obtained from an `http_request`
 * callback. After this call a non-`NULL` pointer is invalid.
 */
void isola_http_response_body_close(struct isola_http_response_body *body);

/**
 * Resolves a hostcall with a JSON result value, consuming the handle.
 *
 * Must be called exactly once per handle. After this call the pointer is
 * invalid. Use `isola_hostcall_response_reject` to deliver an error instead.
 *
 * If the data is not valid JSON, the handle is **not** consumed and the
 * caller may retry with corrected data or call
 * `isola_hostcall_response_reject`.
 *
 * # Safety
 *
 * - `response` must be a live handle obtained from a `hostcall` callback.
 * - `data` must point to a valid JSON buffer of `len` bytes.
 */
enum isola_error_code isola_hostcall_response_resolve(struct isola_hostcall_response *response,
                                                      const uint8_t *data,
                                                      size_t len);

/**
 * Rejects a hostcall with an error message, consuming the handle.
 *
 * Must be called exactly once per handle. After this call the pointer is
 * invalid. Use `isola_hostcall_response_resolve` to deliver a result instead.
 *
 * # Safety
 *
 * - `response` must be a live handle obtained from a `hostcall` callback.
 * - `error_message` must be a valid, null-terminated C string.
 */
enum isola_error_code isola_hostcall_response_reject(struct isola_hostcall_response *response,
                                                     const char *error_message);

/**
 * Cancels a hostcall without a result, consuming the handle.
 *
 * Use this when external work is abandoned. The waiting guest call fails and
 * the response allocation is released.
 *
 * # Safety
 *
 * `response` must be `NULL` or a live handle obtained from a `hostcall`
 * callback.
 */
void isola_hostcall_response_cancel(struct isola_hostcall_response *response);

/**
 * Return the most recent error message produced on the calling thread.
 *
 * The returned pointer is `NULL` until an error occurs. Otherwise it remains
 * valid until the next failing Isola call on the same thread. Successful calls
 * do not clear the stored error.
 */
const char *isola_last_error(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ISOLA_H_INCLUDED */
