#ifndef _ISOLA_H_
#define _ISOLA_H_

/* Don't modify this file manually. It is autogenerated by cbindgen. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum isola_error_code {
  ISOLA_ERROR_CODE_OK = 0,
  ISOLA_ERROR_CODE_INVALID_ARGUMENT = 1,
  ISOLA_ERROR_CODE_INTERNAL = 2,
  ISOLA_ERROR_CODE_STREAM_FULL = 3,
  ISOLA_ERROR_CODE_STREAM_CLOSED = 4,
} isola_error_code;

typedef enum isola_callback_event {
  ISOLA_CALLBACK_EVENT_RESULT_JSON = 0,
  ISOLA_CALLBACK_EVENT_END_JSON = 4,
  ISOLA_CALLBACK_EVENT_STDOUT = 1,
  ISOLA_CALLBACK_EVENT_STDERR = 2,
  ISOLA_CALLBACK_EVENT_ERROR = 3,
} isola_callback_event;

typedef enum isola_argument_type {
  ISOLA_ARGUMENT_TYPE_JSON = 0,
  ISOLA_ARGUMENT_TYPE_JSON_STREAM = 1,
} isola_argument_type;

typedef struct isola_context_handle isola_context_handle;

typedef struct isola_sandbox_handle isola_sandbox_handle;

typedef struct isola_stream_handle isola_stream_handle;

typedef struct isola_blob {
  const uint8_t *data;
  size_t len;
} isola_blob;

typedef union isola_argument_value {
  struct isola_blob data;
  const struct isola_stream_handle *stream;
} isola_argument_value;

typedef struct isola_argument {
  enum isola_argument_type type;
  const char *name;
  union isola_argument_value value;
} isola_argument;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Creates a new isola context with the specified number of threads.
 *
 * # Safety
 *
 * The caller must ensure that `out_context` is a valid pointer to an
 * uninitialized `Box<ContextHandle>`.
 */
enum isola_error_code isola_context_create(int nr_thread,
                                           struct isola_context_handle **out_context);

/**
 * Initializes the isola context with the specified path.
 *
 * # Safety
 *
 * The caller must ensure that `path` is a valid, null-terminated C string.
 */
enum isola_error_code isola_context_initialize(struct isola_context_handle *ctx, const char *path);

/**
 * Sets a configuration value for the isola context.
 *
 * # Safety
 *
 * The caller must ensure that both `key` and `value` are valid, null-terminated C strings.
 */
enum isola_error_code isola_context_config_set(struct isola_context_handle *ctx,
                                               const char *key,
                                               const char *value);

void isola_context_destroy(struct isola_context_handle *_ctx);

/**
 * Creates a new sandbox instance from the context.
 *
 * # Safety
 *
 * The caller must ensure that `out_sandbox` is a valid pointer to an
 * uninitialized `Box<SandboxHandle>`.
 */
enum isola_error_code isola_sandbox_create(struct isola_context_handle *ctx,
                                           struct isola_sandbox_handle **out_sandbox);

void isola_sandbox_destroy(struct isola_sandbox_handle *_sandbox);

/**
 * Sets a configuration value for the sandbox.
 *
 * # Safety
 *
 * The caller must ensure that both `key` and `value` are valid, null-terminated C strings.
 */
enum isola_error_code isola_sandbox_set_config(struct isola_sandbox_handle *sandbox,
                                               const char *key,
                                               const char *value);

enum isola_error_code isola_sandbox_set_callback(struct isola_sandbox_handle *sandbox,
                                                 void (*callback)(enum isola_callback_event,
                                                                  const uint8_t*,
                                                                  size_t,
                                                                  void*),
                                                 void *user_data);

enum isola_error_code isola_sandbox_start(struct isola_sandbox_handle *sandbox);

/**
 * Loads a script into the sandbox.
 *
 * # Safety
 *
 * The caller must ensure that `input` is a valid, null-terminated C string.
 */
enum isola_error_code isola_sandbox_load_script(struct isola_sandbox_handle *sandbox,
                                                const char *input,
                                                uint64_t timeout_in_ms);

/**
 * Runs a function in the sandbox with the specified arguments.
 *
 * # Safety
 *
 * The caller must ensure that:
 * - `func` is a valid, null-terminated C string
 * - `args` is a valid pointer to an array of `Argument` structs of length `args_len`
 * - Each `Argument` in the array has valid pointers and data
 *
 * # Panics
 *
 * This function may panic if argument names contain invalid UTF-8 sequences.
 */
enum isola_error_code isola_sandbox_run(struct isola_sandbox_handle *sandbox,
                                        const char *func,
                                        const struct isola_argument *args,
                                        size_t args_len,
                                        uint64_t timeout_in_ms);

/**
 * Creates a new stream handle for streaming arguments.
 *
 * # Safety
 *
 * The caller must ensure that `out_stream` is a valid pointer to an
 * uninitialized `Box<StreamHandle>`.
 */
enum isola_error_code isola_stream_create(struct isola_stream_handle **out_stream);

/**
 * Pushes data to a stream.
 *
 * # Safety
 *
 * The caller must ensure that `data` points to a valid buffer of length `len`.
 *
 * # Parameters
 *
 * * `blocking` - If non-zero, blocks until space is available in the channel.
 *   If zero, returns immediately with an error if the channel is full.
 */
enum isola_error_code isola_stream_push(const struct isola_stream_handle *stream,
                                        const uint8_t *data,
                                        size_t len,
                                        int blocking);

/**
 * Signals the end of a stream.
 *
 * After calling this function, no more data can be pushed to the stream.
 */
enum isola_error_code isola_stream_end(struct isola_stream_handle *_stream);

void isola_stream_destroy(struct isola_stream_handle *_stream);

const char *isola_last_error(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* _ISOLA_H_ */
