#ifndef _PROMPTKIT_H_
#define _PROMPTKIT_H_

/* Don't modify this file manually. It is autogenerated by cbindgen. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum promptkit_argument_type {
  PROMPTKIT_ARGUMENT_TYPE_JSON = 0,
} promptkit_argument_type;

typedef enum promptkit_callback_event {
  PROMPTKIT_CALLBACK_EVENT_RESULT_JSON = 0,
  PROMPTKIT_CALLBACK_EVENT_END_JSON = 4,
  PROMPTKIT_CALLBACK_EVENT_STDOUT = 1,
  PROMPTKIT_CALLBACK_EVENT_STDERR = 2,
  PROMPTKIT_CALLBACK_EVENT_ERROR = 3,
} promptkit_callback_event;

typedef enum promptkit_error_code {
  PROMPTKIT_ERROR_CODE_OK = 0,
  PROMPTKIT_ERROR_CODE_INVALID_ARGUMENT = 1,
  PROMPTKIT_ERROR_CODE_INTERNAL = 2,
} promptkit_error_code;

typedef struct promptkit_context_handle promptkit_context_handle;

typedef struct promptkit_vm_handle promptkit_vm_handle;

typedef struct promptkit_argument {
  enum promptkit_argument_type type;
  const char *name;
  const uint8_t *value;
  size_t len;
} promptkit_argument;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Creates a new promptkit context with the specified number of threads.
 *
 * # Safety
 *
 * The caller must ensure that `out_context` is a valid pointer to an
 * uninitialized `Box<ContextHandle>`.
 */
enum promptkit_error_code promptkit_context_create(int nr_thread,
                                                   struct promptkit_context_handle **out_context);

/**
 * Initializes the promptkit context with the specified path.
 *
 * # Safety
 *
 * The caller must ensure that `path` is a valid, null-terminated C string.
 */
enum promptkit_error_code promptkit_context_initialize(struct promptkit_context_handle *ctx,
                                                       const char *path);

/**
 * Sets a configuration value for the promptkit context.
 *
 * # Safety
 *
 * The caller must ensure that both `key` and `value` are valid, null-terminated C strings.
 */
enum promptkit_error_code promptkit_context_config_set(struct promptkit_context_handle *ctx,
                                                       const char *key,
                                                       const char *value);

void promptkit_context_destroy(struct promptkit_context_handle *_ctx);

/**
 * Creates a new VM instance from the context.
 *
 * # Safety
 *
 * The caller must ensure that `out_vm` is a valid pointer to an
 * uninitialized `Box<VmHandle>`.
 */
enum promptkit_error_code promptkit_vm_create(struct promptkit_context_handle *ctx,
                                              struct promptkit_vm_handle **out_vm);

void promptkit_vm_destroy(struct promptkit_vm_handle *_vm);

/**
 * Sets a configuration value for the VM.
 *
 * # Safety
 *
 * The caller must ensure that both `key` and `value` are valid, null-terminated C strings.
 */
enum promptkit_error_code promptkit_vm_set_config(struct promptkit_vm_handle *vm,
                                                  const char *key,
                                                  const char *value);

enum promptkit_error_code promptkit_vm_set_callback(struct promptkit_vm_handle *vm,
                                                    void (*callback)(enum promptkit_callback_event,
                                                                     const uint8_t*,
                                                                     size_t,
                                                                     void*),
                                                    void *user_data);

enum promptkit_error_code promptkit_vm_start(struct promptkit_vm_handle *vm);

/**
 * Loads a script into the VM.
 *
 * # Safety
 *
 * The caller must ensure that `input` is a valid, null-terminated C string.
 */
enum promptkit_error_code promptkit_vm_load_script(struct promptkit_vm_handle *vm,
                                                   const char *input,
                                                   uint64_t timeout_in_ms);

/**
 * Runs a function in the VM with the specified arguments.
 *
 * # Safety
 *
 * The caller must ensure that:
 * - `func` is a valid, null-terminated C string
 * - `args` is a valid pointer to an array of `Argument` structs of length `args_len`
 * - Each `Argument` in the array has valid pointers and data
 *
 * # Panics
 *
 * This function may panic if argument names contain invalid UTF-8 sequences.
 */
enum promptkit_error_code promptkit_vm_run(struct promptkit_vm_handle *vm,
                                           const char *func,
                                           const struct promptkit_argument *args,
                                           size_t args_len,
                                           uint64_t timeout_in_ms);

const char *promptkit_last_error(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* _PROMPTKIT_H_ */
