from typing import Any, Literal

import _promptkit_sys as _sys

def fetch(
    method: str,
    url: str,
    params: dict[str, str] | None,
    headers: dict[str, str] | None,
    body: Any | bytes | None,
    timeout: float | None,
) -> _sys.Pollable[Response]: ...
def loads_json(data: str) -> Any: ...

_BufferTypes = Literal["json", "text", "bytes", "binary", "lines", "sse"]

class Buffer:
    def read_all(self) -> Any: ...
    def next(self) -> Any | None: ...

def new_buffer(encoding: _BufferTypes) -> Buffer: ...

class Response:
    def status(self) -> int: ...
    def headers(self) -> dict[str, str]: ...
    def close(self) -> None: ...
    def read_into(self, buf: Buffer, size: int) -> _sys.Pollable[None] | None: ...
    def blocking_read(self, kind: _BufferTypes, size: int) -> Any: ...

FutureResponse = _sys.Pollable[Response]
