from collections.abc import Sequence

class Pollable[T]:
    def release(self) -> None: ...
    def get(self) -> T: ...
    def wait(self) -> T: ...

class ArgIter:
    def read(self) -> tuple[bool, object | None, Pollable[None] | None]: ...

def monotonic() -> float: ...
def poll(poll: Sequence[tuple[Pollable[object], object]], block: bool) -> set[int]: ...
def sleep(duration: float) -> Pollable[None]: ...
