from typing import Any

class Pollable[T]:
    def release(self) -> None: ...
    def get(self) -> T: ...
    def wait(self) -> T: ...

class ArgIter:
    def read(self) -> tuple[bool, Any | None, Pollable[None] | None]: ...

def monotonic() -> float: ...
def poll(poll: list[tuple[Pollable, Any]]) -> set[int]: ...
def sleep(duration: float) -> Pollable[None]: ...
