def debug(message: str, *args, **kwargs) -> None: ...
def info(message: str, *args, **kwargs) -> None: ...
def warning(message: str, *args, **kwargs) -> None: ...
def error(message: str, *args, **kwargs) -> None: ...
