class Descriptor:
    def encode(self, name: str, obj: object) -> bytes: ...
    def decode(self, name: str, data: bytes) -> object: ...

def grpc_reflection(
    url: str, service: str, metadata: dict[str, str] | None, timeout: float | None
) -> tuple[Descriptor, dict[str, tuple[str, str]]]: ...
