interface host {
    variant value {
        cbor(list<u8>),
        cbor-iterator(value-iterator),
    }
    resource value-iterator {
        read: async func() -> option<list<u8>>;
    }
    enum emit-type {
        continuation,
        end,
        partial-result,
    }

    blocking-emit: func(%type: emit-type, %cbor: list<u8>);

    hostcall: async func(%type: string, %payload: list<u8>) -> result<list<u8>, string>;
}
