interface runtime {
    use host.{value};
    enum error-code {
        internal,
        aborted,
    }
    record error {
        code: error-code,
        message: string,
    }
    record argument {
        name: option<string>,
        value: value,
    }

    initialize: func(%preinit: bool, %prelude: option<string>);
    eval-script: async func(%script: string) -> result<_, error>;
    eval-file: async func(%path: string) -> result<_, error>;
    call-func: async func(%func: string, %args: list<argument>) -> result<_, error>;
}
