// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file promptkit/script/v1/error_code.proto (package promptkit.script.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file promptkit/script/v1/error_code.proto.
 */
export const file_promptkit_script_v1_error_code: GenFile = /*@__PURE__*/
  fileDesc("CiRwcm9tcHRraXQvc2NyaXB0L3YxL2Vycm9yX2NvZGUucHJvdG8SE3Byb21wdGtpdC5zY3JpcHQudjEqowEKCUVycm9yQ29kZRIaChZFUlJPUl9DT0RFX1VOU1BFQ0lGSUVEEAASFgoSRVJST1JfQ09ERV9VTktOT1dOEAESIAocRVJST1JfQ09ERV9ERUFETElORV9FWENFRURFRBACEhcKE0VSUk9SX0NPREVfSU5URVJOQUwQAxIcChhFUlJPUl9DT0RFX0dVRVNUX0FCT1JURUQQBCIJCIAIEP////8HQpcBChdjb20ucHJvbXB0a2l0LnNjcmlwdC52MUIORXJyb3JDb2RlUHJvdG9QAaICA1BTWKoCE1Byb21wdGtpdC5TY3JpcHQuVjHKAhNQcm9tcHRraXRcU2NyaXB0XFYx4gIfUHJvbXB0a2l0XFNjcmlwdFxWMVxHUEJNZXRhZGF0YeoCFVByb21wdGtpdDo6U2NyaXB0OjpWMWIGcHJvdG8z");

/**
 * @generated from enum promptkit.script.v1.ErrorCode
 */
export enum ErrorCode {
  /**
   * @generated from enum value: ERROR_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ERROR_CODE_UNKNOWN = 1;
   */
  UNKNOWN = 1,

  /**
   * @generated from enum value: ERROR_CODE_DEADLINE_EXCEEDED = 2;
   */
  DEADLINE_EXCEEDED = 2,

  /**
   * @generated from enum value: ERROR_CODE_INTERNAL = 3;
   */
  INTERNAL = 3,

  /**
   * @generated from enum value: ERROR_CODE_GUEST_ABORTED = 4;
   */
  GUEST_ABORTED = 4,
}

/**
 * Describes the enum promptkit.script.v1.ErrorCode.
 */
export const ErrorCodeSchema: GenEnum<ErrorCode> = /*@__PURE__*/
  enumDesc(file_promptkit_script_v1_error_code, 0);

