// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file promptkit/script/v1/error_code.proto (package promptkit.script.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum promptkit.script.v1.ErrorCode
 */
export enum ErrorCode {
  /**
   * @generated from enum value: ERROR_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ERROR_CODE_UNKNOWN = 1;
   */
  UNKNOWN = 1,

  /**
   * @generated from enum value: ERROR_CODE_DEADLINE_EXCEEDED = 2;
   */
  DEADLINE_EXCEEDED = 2,

  /**
   * @generated from enum value: ERROR_CODE_INTERNAL = 3;
   */
  INTERNAL = 3,

  /**
   * @generated from enum value: ERROR_CODE_GUEST_ABORTED = 4;
   */
  GUEST_ABORTED = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(ErrorCode)
proto3.util.setEnumType(ErrorCode, "promptkit.script.v1.ErrorCode", [
  { no: 0, name: "ERROR_CODE_UNSPECIFIED" },
  { no: 1, name: "ERROR_CODE_UNKNOWN" },
  { no: 2, name: "ERROR_CODE_DEADLINE_EXCEEDED" },
  { no: 3, name: "ERROR_CODE_INTERNAL" },
  { no: 4, name: "ERROR_CODE_GUEST_ABORTED" },
]);

