// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file promptkit/script/v1/service.proto (package promptkit.script.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AnalyzeRequest, AnalyzeResponse, ExecuteClientStreamRequest, ExecuteClientStreamResponse, ExecuteRequest, ExecuteResponse, ExecuteServerStreamRequest, ExecuteServerStreamResponse, ExecuteStreamRequest, ExecuteStreamResponse, ListRuntimeRequest, ListRuntimeResponse } from "./service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service promptkit.script.v1.ScriptService
 */
export const ScriptService = {
  typeName: "promptkit.script.v1.ScriptService",
  methods: {
    /**
     * @generated from rpc promptkit.script.v1.ScriptService.ListRuntime
     */
    listRuntime: {
      name: "ListRuntime",
      I: ListRuntimeRequest,
      O: ListRuntimeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc promptkit.script.v1.ScriptService.Analyze
     */
    analyze: {
      name: "Analyze",
      I: AnalyzeRequest,
      O: AnalyzeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc promptkit.script.v1.ScriptService.Execute
     */
    execute: {
      name: "Execute",
      I: ExecuteRequest,
      O: ExecuteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc promptkit.script.v1.ScriptService.ExecuteClientStream
     */
    executeClientStream: {
      name: "ExecuteClientStream",
      I: ExecuteClientStreamRequest,
      O: ExecuteClientStreamResponse,
      kind: MethodKind.ClientStreaming,
    },
    /**
     * @generated from rpc promptkit.script.v1.ScriptService.ExecuteServerStream
     */
    executeServerStream: {
      name: "ExecuteServerStream",
      I: ExecuteServerStreamRequest,
      O: ExecuteServerStreamResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc promptkit.script.v1.ScriptService.ExecuteStream
     */
    executeStream: {
      name: "ExecuteStream",
      I: ExecuteStreamRequest,
      O: ExecuteStreamResponse,
      kind: MethodKind.BiDiStreaming,
    },
  }
} as const;

