// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file promptkit/script/v1/trace.proto (package promptkit.script.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from enum promptkit.script.v1.TraceLevel
 */
export enum TraceLevel {
  /**
   * @generated from enum value: TRACE_LEVEL_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: TRACE_LEVEL_NONE = 1;
   */
  NONE = 1,

  /**
   * @generated from enum value: TRACE_LEVEL_ALL = 2;
   */
  ALL = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(TraceLevel)
proto3.util.setEnumType(TraceLevel, "promptkit.script.v1.TraceLevel", [
  { no: 0, name: "TRACE_LEVEL_UNSPECIFIED" },
  { no: 1, name: "TRACE_LEVEL_NONE" },
  { no: 2, name: "TRACE_LEVEL_ALL" },
]);

/**
 * @generated from message promptkit.script.v1.Trace
 */
export class Trace extends Message<Trace> {
  /**
   * @generated from field: int32 id = 1;
   */
  id = 0;

  /**
   * @generated from field: string group = 2;
   */
  group = "";

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 3;
   */
  timestamp?: Timestamp;

  /**
   * @generated from oneof promptkit.script.v1.Trace.trace_type
   */
  traceType: {
    /**
     * @generated from field: promptkit.script.v1.Trace.Log log = 4;
     */
    value: Trace_Log;
    case: "log";
  } | {
    /**
     * @generated from field: promptkit.script.v1.Trace.Event event = 5;
     */
    value: Trace_Event;
    case: "event";
  } | {
    /**
     * @generated from field: promptkit.script.v1.Trace.SpanBegin span_begin = 6;
     */
    value: Trace_SpanBegin;
    case: "spanBegin";
  } | {
    /**
     * @generated from field: promptkit.script.v1.Trace.SpanEnd span_end = 7;
     */
    value: Trace_SpanEnd;
    case: "spanEnd";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<Trace>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "promptkit.script.v1.Trace";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "group", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "timestamp", kind: "message", T: Timestamp },
    { no: 4, name: "log", kind: "message", T: Trace_Log, oneof: "trace_type" },
    { no: 5, name: "event", kind: "message", T: Trace_Event, oneof: "trace_type" },
    { no: 6, name: "span_begin", kind: "message", T: Trace_SpanBegin, oneof: "trace_type" },
    { no: 7, name: "span_end", kind: "message", T: Trace_SpanEnd, oneof: "trace_type" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Trace {
    return new Trace().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Trace {
    return new Trace().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Trace {
    return new Trace().fromJsonString(jsonString, options);
  }

  static equals(a: Trace | PlainMessage<Trace> | undefined, b: Trace | PlainMessage<Trace> | undefined): boolean {
    return proto3.util.equals(Trace, a, b);
  }
}

/**
 * @generated from message promptkit.script.v1.Trace.Log
 */
export class Trace_Log extends Message<Trace_Log> {
  /**
   * @generated from field: string content = 1;
   */
  content = "";

  constructor(data?: PartialMessage<Trace_Log>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "promptkit.script.v1.Trace.Log";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Trace_Log {
    return new Trace_Log().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Trace_Log {
    return new Trace_Log().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Trace_Log {
    return new Trace_Log().fromJsonString(jsonString, options);
  }

  static equals(a: Trace_Log | PlainMessage<Trace_Log> | undefined, b: Trace_Log | PlainMessage<Trace_Log> | undefined): boolean {
    return proto3.util.equals(Trace_Log, a, b);
  }
}

/**
 * @generated from message promptkit.script.v1.Trace.Event
 */
export class Trace_Event extends Message<Trace_Event> {
  /**
   * @generated from field: string kind = 1;
   */
  kind = "";

  /**
   * @generated from field: int32 parent_id = 2;
   */
  parentId = 0;

  /**
   * @generated from field: map<string, string> data = 3;
   */
  data: { [key: string]: string } = {};

  constructor(data?: PartialMessage<Trace_Event>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "promptkit.script.v1.Trace.Event";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "kind", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "parent_id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "data", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Trace_Event {
    return new Trace_Event().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Trace_Event {
    return new Trace_Event().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Trace_Event {
    return new Trace_Event().fromJsonString(jsonString, options);
  }

  static equals(a: Trace_Event | PlainMessage<Trace_Event> | undefined, b: Trace_Event | PlainMessage<Trace_Event> | undefined): boolean {
    return proto3.util.equals(Trace_Event, a, b);
  }
}

/**
 * @generated from message promptkit.script.v1.Trace.SpanBegin
 */
export class Trace_SpanBegin extends Message<Trace_SpanBegin> {
  /**
   * @generated from field: string kind = 1;
   */
  kind = "";

  /**
   * @generated from field: int32 parent_id = 2;
   */
  parentId = 0;

  /**
   * @generated from field: map<string, string> data = 3;
   */
  data: { [key: string]: string } = {};

  constructor(data?: PartialMessage<Trace_SpanBegin>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "promptkit.script.v1.Trace.SpanBegin";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "kind", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "parent_id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "data", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Trace_SpanBegin {
    return new Trace_SpanBegin().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Trace_SpanBegin {
    return new Trace_SpanBegin().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Trace_SpanBegin {
    return new Trace_SpanBegin().fromJsonString(jsonString, options);
  }

  static equals(a: Trace_SpanBegin | PlainMessage<Trace_SpanBegin> | undefined, b: Trace_SpanBegin | PlainMessage<Trace_SpanBegin> | undefined): boolean {
    return proto3.util.equals(Trace_SpanBegin, a, b);
  }
}

/**
 * @generated from message promptkit.script.v1.Trace.SpanEnd
 */
export class Trace_SpanEnd extends Message<Trace_SpanEnd> {
  /**
   * @generated from field: int32 parent_id = 1;
   */
  parentId = 0;

  /**
   * @generated from field: map<string, string> data = 2;
   */
  data: { [key: string]: string } = {};

  constructor(data?: PartialMessage<Trace_SpanEnd>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "promptkit.script.v1.Trace.SpanEnd";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "parent_id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "data", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Trace_SpanEnd {
    return new Trace_SpanEnd().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Trace_SpanEnd {
    return new Trace_SpanEnd().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Trace_SpanEnd {
    return new Trace_SpanEnd().fromJsonString(jsonString, options);
  }

  static equals(a: Trace_SpanEnd | PlainMessage<Trace_SpanEnd> | undefined, b: Trace_SpanEnd | PlainMessage<Trace_SpanEnd> | undefined): boolean {
    return proto3.util.equals(Trace_SpanEnd, a, b);
  }
}

