// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file promptkit/script/v1/trace.proto (package promptkit.script.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file promptkit/script/v1/trace.proto.
 */
export const file_promptkit_script_v1_trace: GenFile = /*@__PURE__*/
  fileDesc("Ch9wcm9tcHRraXQvc2NyaXB0L3YxL3RyYWNlLnByb3RvEhNwcm9tcHRraXQuc2NyaXB0LnYxIpIGCgVUcmFjZRIKCgJpZBgBIAEoBRINCgVncm91cBgCIAEoCRItCgl0aW1lc3RhbXAYAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi0KA2xvZxgEIAEoCzIeLnByb21wdGtpdC5zY3JpcHQudjEuVHJhY2UuTG9nSAASMQoFZXZlbnQYBSABKAsyIC5wcm9tcHRraXQuc2NyaXB0LnYxLlRyYWNlLkV2ZW50SAASOgoKc3Bhbl9iZWdpbhgGIAEoCzIkLnByb21wdGtpdC5zY3JpcHQudjEuVHJhY2UuU3BhbkJlZ2luSAASNgoIc3Bhbl9lbmQYByABKAsyIi5wcm9tcHRraXQuc2NyaXB0LnYxLlRyYWNlLlNwYW5FbmRIABonCgNMb2cSDwoHY29udGVudBgBIAEoCRIPCgdjb250ZXh0GAIgASgJGo8BCgVFdmVudBIMCgRraW5kGAEgASgJEhEKCXBhcmVudF9pZBgCIAEoBRI4CgRkYXRhGAMgAygLMioucHJvbXB0a2l0LnNjcmlwdC52MS5UcmFjZS5FdmVudC5EYXRhRW50cnkaKwoJRGF0YUVudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEalwEKCVNwYW5CZWdpbhIMCgRraW5kGAEgASgJEhEKCXBhcmVudF9pZBgCIAEoBRI8CgRkYXRhGAMgAygLMi4ucHJvbXB0a2l0LnNjcmlwdC52MS5UcmFjZS5TcGFuQmVnaW4uRGF0YUVudHJ5GisKCURhdGFFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBGoUBCgdTcGFuRW5kEhEKCXBhcmVudF9pZBgBIAEoBRI6CgRkYXRhGAIgAygLMiwucHJvbXB0a2l0LnNjcmlwdC52MS5UcmFjZS5TcGFuRW5kLkRhdGFFbnRyeRorCglEYXRhRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4AUIMCgp0cmFjZV90eXBlKlQKClRyYWNlTGV2ZWwSGwoXVFJBQ0VfTEVWRUxfVU5TUEVDSUZJRUQQABIUChBUUkFDRV9MRVZFTF9OT05FEAESEwoPVFJBQ0VfTEVWRUxfQUxMEAJCkwEKF2NvbS5wcm9tcHRraXQuc2NyaXB0LnYxQgpUcmFjZVByb3RvUAGiAgNQU1iqAhNQcm9tcHRraXQuU2NyaXB0LlYxygITUHJvbXB0a2l0XFNjcmlwdFxWMeICH1Byb21wdGtpdFxTY3JpcHRcVjFcR1BCTWV0YWRhdGHqAhVQcm9tcHRraXQ6OlNjcmlwdDo6VjFiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * @generated from message promptkit.script.v1.Trace
 */
export type Trace = Message<"promptkit.script.v1.Trace"> & {
  /**
   * @generated from field: int32 id = 1;
   */
  id: number;

  /**
   * @generated from field: string group = 2;
   */
  group: string;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 3;
   */
  timestamp?: Timestamp;

  /**
   * @generated from oneof promptkit.script.v1.Trace.trace_type
   */
  traceType: {
    /**
     * @generated from field: promptkit.script.v1.Trace.Log log = 4;
     */
    value: Trace_Log;
    case: "log";
  } | {
    /**
     * @generated from field: promptkit.script.v1.Trace.Event event = 5;
     */
    value: Trace_Event;
    case: "event";
  } | {
    /**
     * @generated from field: promptkit.script.v1.Trace.SpanBegin span_begin = 6;
     */
    value: Trace_SpanBegin;
    case: "spanBegin";
  } | {
    /**
     * @generated from field: promptkit.script.v1.Trace.SpanEnd span_end = 7;
     */
    value: Trace_SpanEnd;
    case: "spanEnd";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message promptkit.script.v1.Trace.
 * Use `create(TraceSchema)` to create a new message.
 */
export const TraceSchema: GenMessage<Trace> = /*@__PURE__*/
  messageDesc(file_promptkit_script_v1_trace, 0);

/**
 * @generated from message promptkit.script.v1.Trace.Log
 */
export type Trace_Log = Message<"promptkit.script.v1.Trace.Log"> & {
  /**
   * @generated from field: string content = 1;
   */
  content: string;

  /**
   * @generated from field: string context = 2;
   */
  context: string;
};

/**
 * Describes the message promptkit.script.v1.Trace.Log.
 * Use `create(Trace_LogSchema)` to create a new message.
 */
export const Trace_LogSchema: GenMessage<Trace_Log> = /*@__PURE__*/
  messageDesc(file_promptkit_script_v1_trace, 0, 0);

/**
 * @generated from message promptkit.script.v1.Trace.Event
 */
export type Trace_Event = Message<"promptkit.script.v1.Trace.Event"> & {
  /**
   * @generated from field: string kind = 1;
   */
  kind: string;

  /**
   * @generated from field: int32 parent_id = 2;
   */
  parentId: number;

  /**
   * @generated from field: map<string, string> data = 3;
   */
  data: { [key: string]: string };
};

/**
 * Describes the message promptkit.script.v1.Trace.Event.
 * Use `create(Trace_EventSchema)` to create a new message.
 */
export const Trace_EventSchema: GenMessage<Trace_Event> = /*@__PURE__*/
  messageDesc(file_promptkit_script_v1_trace, 0, 1);

/**
 * @generated from message promptkit.script.v1.Trace.SpanBegin
 */
export type Trace_SpanBegin = Message<"promptkit.script.v1.Trace.SpanBegin"> & {
  /**
   * @generated from field: string kind = 1;
   */
  kind: string;

  /**
   * @generated from field: int32 parent_id = 2;
   */
  parentId: number;

  /**
   * @generated from field: map<string, string> data = 3;
   */
  data: { [key: string]: string };
};

/**
 * Describes the message promptkit.script.v1.Trace.SpanBegin.
 * Use `create(Trace_SpanBeginSchema)` to create a new message.
 */
export const Trace_SpanBeginSchema: GenMessage<Trace_SpanBegin> = /*@__PURE__*/
  messageDesc(file_promptkit_script_v1_trace, 0, 2);

/**
 * @generated from message promptkit.script.v1.Trace.SpanEnd
 */
export type Trace_SpanEnd = Message<"promptkit.script.v1.Trace.SpanEnd"> & {
  /**
   * @generated from field: int32 parent_id = 1;
   */
  parentId: number;

  /**
   * @generated from field: map<string, string> data = 2;
   */
  data: { [key: string]: string };
};

/**
 * Describes the message promptkit.script.v1.Trace.SpanEnd.
 * Use `create(Trace_SpanEndSchema)` to create a new message.
 */
export const Trace_SpanEndSchema: GenMessage<Trace_SpanEnd> = /*@__PURE__*/
  messageDesc(file_promptkit_script_v1_trace, 0, 3);

/**
 * @generated from enum promptkit.script.v1.TraceLevel
 */
export enum TraceLevel {
  /**
   * @generated from enum value: TRACE_LEVEL_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: TRACE_LEVEL_NONE = 1;
   */
  NONE = 1,

  /**
   * @generated from enum value: TRACE_LEVEL_ALL = 2;
   */
  ALL = 2,
}

/**
 * Describes the enum promptkit.script.v1.TraceLevel.
 */
export const TraceLevelSchema: GenEnum<TraceLevel> = /*@__PURE__*/
  enumDesc(file_promptkit_script_v1_trace, 0);

