# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: promptkit/script/v1/error_code.proto, promptkit/script/v1/service.proto, promptkit/script/v1/trace.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from datetime import (
    datetime,
    timedelta,
)
from typing import (
    TYPE_CHECKING,
    AsyncIterable,
    AsyncIterator,
    Dict,
    Iterable,
    List,
    Optional,
    Union,
)

import betterproto
import betterproto.lib.google.protobuf as betterproto_lib_google_protobuf
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase


if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


class ErrorCode(betterproto.Enum):
    UNSPECIFIED = 0
    UNKNOWN = 1
    DEADLINE_EXCEEDED = 2
    INTERNAL = 3
    GUEST_ABORTED = 4


class TraceLevel(betterproto.Enum):
    UNSPECIFIED = 0
    NONE = 1
    ALL = 2


class ContentType(betterproto.Enum):
    UNSPECIFIED = 0
    PROTOBUF_VALUE = 1
    JSON = 2
    CBOR = 3


class ArgumentMarker(betterproto.Enum):
    MARKER_UNSPECIFIED = 0
    MARKER_STREAM = 1
    MARKER_STREAM_CONTROL_CLOSE = 2


@dataclass(eq=False, repr=False)
class Trace(betterproto.Message):
    id: int = betterproto.int32_field(1)
    group: str = betterproto.string_field(2)
    timestamp: datetime = betterproto.message_field(3)
    log: "TraceLog" = betterproto.message_field(4, group="trace_type")
    event: "TraceEvent" = betterproto.message_field(5, group="trace_type")
    span_begin: "TraceSpanBegin" = betterproto.message_field(6, group="trace_type")
    span_end: "TraceSpanEnd" = betterproto.message_field(7, group="trace_type")


@dataclass(eq=False, repr=False)
class TraceLog(betterproto.Message):
    content: str = betterproto.string_field(1)
    context: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class TraceEvent(betterproto.Message):
    kind: str = betterproto.string_field(1)
    parent_id: int = betterproto.int32_field(2)
    data: Dict[str, str] = betterproto.map_field(
        3, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class TraceSpanBegin(betterproto.Message):
    kind: str = betterproto.string_field(1)
    parent_id: int = betterproto.int32_field(2)
    data: Dict[str, str] = betterproto.map_field(
        3, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class TraceSpanEnd(betterproto.Message):
    parent_id: int = betterproto.int32_field(1)
    data: Dict[str, str] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class ScriptInline(betterproto.Message):
    script: str = betterproto.string_field(1)
    runtime: str = betterproto.string_field(3)
    prelude: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class Source(betterproto.Message):
    script_inline: "ScriptInline" = betterproto.message_field(1, group="source_type")
    bundle_inline: bytes = betterproto.bytes_field(2, group="source_type")


@dataclass(eq=False, repr=False)
class Argument(betterproto.Message):
    value: "betterproto_lib_google_protobuf.Value" = betterproto.message_field(
        1, group="argument_type"
    )
    json: str = betterproto.string_field(2, group="argument_type")
    cbor: bytes = betterproto.bytes_field(3, group="argument_type")
    marker: "ArgumentMarker" = betterproto.enum_field(15, group="argument_type")
    name: str = betterproto.string_field(4)
    """named arguments"""


@dataclass(eq=False, repr=False)
class Error(betterproto.Message):
    code: int = betterproto.int32_field(1)
    message: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class Result(betterproto.Message):
    value: "betterproto_lib_google_protobuf.Value" = betterproto.message_field(
        1, group="result_type"
    )
    json: str = betterproto.string_field(2, group="result_type")
    cbor: bytes = betterproto.bytes_field(3, group="result_type")
    error: "Error" = betterproto.message_field(15, group="result_type")


@dataclass(eq=False, repr=False)
class ExecutionSpec(betterproto.Message):
    timeout: timedelta = betterproto.message_field(1)
    arguments: List["Argument"] = betterproto.message_field(2)
    method: str = betterproto.string_field(3)
    trace_level: "TraceLevel" = betterproto.enum_field(20)


@dataclass(eq=False, repr=False)
class ExecutionMetadata(betterproto.Message):
    traces: List["Trace"] = betterproto.message_field(20)


@dataclass(eq=False, repr=False)
class ExecutionStreamMetadata(betterproto.Message):
    traces: List["Trace"] = betterproto.message_field(20)


@dataclass(eq=False, repr=False)
class ExecuteRequest(betterproto.Message):
    source: "Source" = betterproto.message_field(1)
    spec: "ExecutionSpec" = betterproto.message_field(2)
    result_content_type: List["ContentType"] = betterproto.enum_field(3)


@dataclass(eq=False, repr=False)
class InitialExecuteRequest(betterproto.Message):
    source: "Source" = betterproto.message_field(1)
    spec: "ExecutionSpec" = betterproto.message_field(2)
    result_content_type: List["ContentType"] = betterproto.enum_field(3)


@dataclass(eq=False, repr=False)
class ExecuteServerStreamRequest(betterproto.Message):
    source: "Source" = betterproto.message_field(1)
    spec: "ExecutionSpec" = betterproto.message_field(2)
    result_content_type: List["ContentType"] = betterproto.enum_field(3)


@dataclass(eq=False, repr=False)
class ExecuteClientStreamRequest(betterproto.Message):
    initial_request: "InitialExecuteRequest" = betterproto.message_field(
        1, group="request_type"
    )
    stream_value: "Argument" = betterproto.message_field(2, group="request_type")
    timeout: timedelta = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class ExecuteStreamRequest(betterproto.Message):
    initial_request: "InitialExecuteRequest" = betterproto.message_field(
        1, group="request_type"
    )
    stream_value: "Argument" = betterproto.message_field(2, group="request_type")
    timeout: timedelta = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class ExecuteResponse(betterproto.Message):
    result: "Result" = betterproto.message_field(1)
    metadata: "ExecutionMetadata" = betterproto.message_field(15)


@dataclass(eq=False, repr=False)
class ExecuteClientStreamResponse(betterproto.Message):
    result: "Result" = betterproto.message_field(1)
    metadata: "ExecutionMetadata" = betterproto.message_field(15)


@dataclass(eq=False, repr=False)
class ExecuteServerStreamResponse(betterproto.Message):
    result: "Result" = betterproto.message_field(1)
    metadata: "ExecutionStreamMetadata" = betterproto.message_field(15)


@dataclass(eq=False, repr=False)
class ExecuteStreamResponse(betterproto.Message):
    result: "Result" = betterproto.message_field(1)
    metadata: "ExecutionStreamMetadata" = betterproto.message_field(15)


@dataclass(eq=False, repr=False)
class ListRuntimeRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ListRuntimeResponse(betterproto.Message):
    runtimes: List["Runtime"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class Runtime(betterproto.Message):
    name: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class AnalyzeRequest(betterproto.Message):
    source: "Source" = betterproto.message_field(1)
    spec: "ExecutionSpec" = betterproto.message_field(2)
    methods: List[str] = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class TypeInfo(betterproto.Message):
    name: str = betterproto.string_field(1)
    json_schema: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class MethodInfo(betterproto.Message):
    name: str = betterproto.string_field(1)
    description: str = betterproto.string_field(2)
    argument_types: List["TypeInfo"] = betterproto.message_field(3)
    result_type: "TypeInfo" = betterproto.message_field(4)


@dataclass(eq=False, repr=False)
class AnalyzeResult(betterproto.Message):
    method_infos: List["MethodInfo"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class AnalyzeResponse(betterproto.Message):
    analyze_result: "AnalyzeResult" = betterproto.message_field(1, group="result_type")
    error: "Error" = betterproto.message_field(15, group="result_type")


class ScriptServiceStub(betterproto.ServiceStub):
    async def list_runtime(
        self,
        list_runtime_request: "ListRuntimeRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ListRuntimeResponse":
        return await self._unary_unary(
            "/promptkit.script.v1.ScriptService/ListRuntime",
            list_runtime_request,
            ListRuntimeResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def analyze(
        self,
        analyze_request: "AnalyzeRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "AnalyzeResponse":
        return await self._unary_unary(
            "/promptkit.script.v1.ScriptService/Analyze",
            analyze_request,
            AnalyzeResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def execute(
        self,
        execute_request: "ExecuteRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ExecuteResponse":
        return await self._unary_unary(
            "/promptkit.script.v1.ScriptService/Execute",
            execute_request,
            ExecuteResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def execute_client_stream(
        self,
        execute_client_stream_request_iterator: Union[
            AsyncIterable[ExecuteClientStreamRequest],
            Iterable[ExecuteClientStreamRequest],
        ],
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ExecuteClientStreamResponse":
        return await self._stream_unary(
            "/promptkit.script.v1.ScriptService/ExecuteClientStream",
            execute_client_stream_request_iterator,
            ExecuteClientStreamRequest,
            ExecuteClientStreamResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def execute_server_stream(
        self,
        execute_server_stream_request: "ExecuteServerStreamRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> AsyncIterator[ExecuteServerStreamResponse]:
        async for response in self._unary_stream(
            "/promptkit.script.v1.ScriptService/ExecuteServerStream",
            execute_server_stream_request,
            ExecuteServerStreamResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        ):
            yield response

    async def execute_stream(
        self,
        execute_stream_request_iterator: Union[
            AsyncIterable[ExecuteStreamRequest], Iterable[ExecuteStreamRequest]
        ],
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> AsyncIterator[ExecuteStreamResponse]:
        async for response in self._stream_stream(
            "/promptkit.script.v1.ScriptService/ExecuteStream",
            execute_stream_request_iterator,
            ExecuteStreamRequest,
            ExecuteStreamResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        ):
            yield response


class ScriptServiceBase(ServiceBase):

    async def list_runtime(
        self, list_runtime_request: "ListRuntimeRequest"
    ) -> "ListRuntimeResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def analyze(self, analyze_request: "AnalyzeRequest") -> "AnalyzeResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def execute(self, execute_request: "ExecuteRequest") -> "ExecuteResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def execute_client_stream(
        self,
        execute_client_stream_request_iterator: AsyncIterator[
            ExecuteClientStreamRequest
        ],
    ) -> "ExecuteClientStreamResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def execute_server_stream(
        self, execute_server_stream_request: "ExecuteServerStreamRequest"
    ) -> AsyncIterator[ExecuteServerStreamResponse]:
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)
        yield ExecuteServerStreamResponse()

    async def execute_stream(
        self, execute_stream_request_iterator: AsyncIterator[ExecuteStreamRequest]
    ) -> AsyncIterator[ExecuteStreamResponse]:
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)
        yield ExecuteStreamResponse()

    async def __rpc_list_runtime(
        self, stream: "grpclib.server.Stream[ListRuntimeRequest, ListRuntimeResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.list_runtime(request)
        await stream.send_message(response)

    async def __rpc_analyze(
        self, stream: "grpclib.server.Stream[AnalyzeRequest, AnalyzeResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.analyze(request)
        await stream.send_message(response)

    async def __rpc_execute(
        self, stream: "grpclib.server.Stream[ExecuteRequest, ExecuteResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.execute(request)
        await stream.send_message(response)

    async def __rpc_execute_client_stream(
        self,
        stream: "grpclib.server.Stream[ExecuteClientStreamRequest, ExecuteClientStreamResponse]",
    ) -> None:
        request = stream.__aiter__()
        response = await self.execute_client_stream(request)
        await stream.send_message(response)

    async def __rpc_execute_server_stream(
        self,
        stream: "grpclib.server.Stream[ExecuteServerStreamRequest, ExecuteServerStreamResponse]",
    ) -> None:
        request = await stream.recv_message()
        await self._call_rpc_handler_server_stream(
            self.execute_server_stream,
            stream,
            request,
        )

    async def __rpc_execute_stream(
        self,
        stream: "grpclib.server.Stream[ExecuteStreamRequest, ExecuteStreamResponse]",
    ) -> None:
        request = stream.__aiter__()
        await self._call_rpc_handler_server_stream(
            self.execute_stream,
            stream,
            request,
        )

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/promptkit.script.v1.ScriptService/ListRuntime": grpclib.const.Handler(
                self.__rpc_list_runtime,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListRuntimeRequest,
                ListRuntimeResponse,
            ),
            "/promptkit.script.v1.ScriptService/Analyze": grpclib.const.Handler(
                self.__rpc_analyze,
                grpclib.const.Cardinality.UNARY_UNARY,
                AnalyzeRequest,
                AnalyzeResponse,
            ),
            "/promptkit.script.v1.ScriptService/Execute": grpclib.const.Handler(
                self.__rpc_execute,
                grpclib.const.Cardinality.UNARY_UNARY,
                ExecuteRequest,
                ExecuteResponse,
            ),
            "/promptkit.script.v1.ScriptService/ExecuteClientStream": grpclib.const.Handler(
                self.__rpc_execute_client_stream,
                grpclib.const.Cardinality.STREAM_UNARY,
                ExecuteClientStreamRequest,
                ExecuteClientStreamResponse,
            ),
            "/promptkit.script.v1.ScriptService/ExecuteServerStream": grpclib.const.Handler(
                self.__rpc_execute_server_stream,
                grpclib.const.Cardinality.UNARY_STREAM,
                ExecuteServerStreamRequest,
                ExecuteServerStreamResponse,
            ),
            "/promptkit.script.v1.ScriptService/ExecuteStream": grpclib.const.Handler(
                self.__rpc_execute_stream,
                grpclib.const.Cardinality.STREAM_STREAM,
                ExecuteStreamRequest,
                ExecuteStreamResponse,
            ),
        }
