from typing import Literal

import _isola_sys as _sys

def fetch(
    method: str,
    url: str,
    params: dict[str, str] | None,
    headers: dict[str, str] | None,
    body: object | bytes | None,
    timeout: float | None,
) -> _sys.Pollable[Response]: ...
def ws_connect(
    url: str,
    headers: dict[str, str] | None,
    timeout: float | None,
) -> _sys.Pollable[Websocket]: ...
def loads_json(data: str) -> object: ...

type _BufferTypes = Literal["json", "text", "bytes", "binary", "lines", "sse"]

class Buffer:
    def read_all(self) -> object | bytes | str: ...
    def next(self) -> object | bytes | str | None: ...

def new_buffer(encoding: _BufferTypes) -> Buffer: ...

class Response:
    def status(self) -> int: ...
    def headers(self) -> dict[str, str]: ...
    def close(self) -> None: ...
    def read_into(self, buf: Buffer, size: int) -> _sys.Pollable[None] | None: ...
    def blocking_read(self, kind: _BufferTypes, size: int) -> object: ...

class Websocket:
    def recv(
        self,
    ) -> (
        tuple[Literal[False], None, None]
        | tuple[Literal[True], str | bytes, None]
        | tuple[Literal[True], None, _sys.Pollable[None]]
    ): ...
    def send(self, data: str | bytes) -> _sys.Pollable[None] | None: ...
    def close(
        self, code: int | None, reason: str | None
    ) -> _sys.Pollable[None] | None: ...
    def shutdown(self) -> None: ...
    def headers(self) -> dict[str, str]: ...
