#![expect(
    clippy::same_length_and_capacity,
    reason = "generated by wit_bindgen::generate! macro"
)]

pub mod wasi_http;

pub use wit_bindgen::block_on;

wit_bindgen::generate!({
    world: "sandbox",
    path: "../isola/wit",
    generate_all,
    pub_export_macro: true,
});
