#![expect(
    clippy::same_length_and_capacity,
    reason = "generated by wit_bindgen::generate! macro"
)]

mod cbor;
pub mod lifecycle;
pub mod pending;
mod time;
pub mod wasi_http;

pub use cbor::CallbackWriter;
pub use time::{Deadline, DeadlineOverflow, monotonic};
pub use wit_bindgen::block_on;

wit_bindgen::generate!({
    world: "sandbox",
    path: "../isola/wit",
    generate_all,
    pub_export_macro: true,
});
