package promptkit:script;

interface guest {
    use host.{value};
    use wasi:logging/logging@0.1.0-draft.{level};
    enum error-code {
        unknown,
        internal,
        aborted,
    }
    record error {
        code: error-code,
        message: string,
    }
    record argument {
        name: option<string>,
        value: value,
    }

    initialize: func(%preinit: bool) -> ();
    set-log-level: func(%level: option<level>) -> ();
    eval-script: func(%script: string) -> result<_, error>;
    call-func: func(%func: string, %args: list<argument>) -> result<option<list<u8>>, error>;
}
