interface host {
    use wasi:io/poll@0.2.6.{pollable};
    use wasi:io/streams@0.2.6.{stream-error};

    variant value {
        cbor(list<u8>),
        iterator(value-iterator),
    }
    resource value-iterator {
        read: func() -> option<result<value, stream-error>>;
        blocking-read: func() -> result<value, stream-error>;
        subscribe: func() -> pollable;
    }
    emit: func(%cbor: list<u8>);
}
