package promptkit:script;

interface host-api {
    variant argument {
        cbor(list<u8>),
        iterator(argument-iterator),
    }
    resource argument-iterator {
        read: func() -> option<argument>;
    }
    emit: func(%cbor: list<u8>);
}

interface guest-api {
    use host-api.{argument};
    enum error-code {
        unknown,
        internal,
        aborted,
    }
    record error {
        code: error-code,
        message: string,
    }

    eval-bundle: func(%bundle-path: string, entrypoint: string) -> result<_, error>;
    eval-script: func(%script: string) -> result<_, error>;
    call-func: func(%func: string, %args: list<argument>) -> result<option<list<u8>>, error>;
}

world sandbox {
    import http-client;
    import host-api;
    export guest-api;
}
