// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file promptkit/llm/v1/llm.proto (package promptkit.llm.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { RemoteFile } from "../../common/v1/common_pb";
import { file_promptkit_common_v1_common } from "../../common/v1/common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file promptkit/llm/v1/llm.proto.
 */
export const file_promptkit_llm_v1_llm: GenFile = /*@__PURE__*/
  fileDesc("Chpwcm9tcHRraXQvbGxtL3YxL2xsbS5wcm90bxIQcHJvbXB0a2l0LmxsbS52MSI8CglMTE1Db25maWcSLwoKdG9rZW5pemVycxgBIAMoCzIbLnByb21wdGtpdC5sbG0udjEuVG9rZW5pemVyIsEBCglUb2tlbml6ZXISDAoEbmFtZRgBIAEoCRIuCgR0eXBlGAIgASgOMiAucHJvbXB0a2l0LmxsbS52MS5Ub2tlbml6ZXIuVHlwZRI2CgtyZW1vdGVfZmlsZRgDIAEoCzIfLnByb21wdGtpdC5jb21tb24udjEuUmVtb3RlRmlsZUgAIjQKBFR5cGUSFAoQVFlQRV9VTlNQRUNJRklFRBAAEhYKElRZUEVfU0VOVEVOQ0VQSUVDRRABQggKBnNvdXJjZUKCAQoUY29tLnByb21wdGtpdC5sbG0udjFCCExsbVByb3RvUAGiAgNQTFiqAhBQcm9tcHRraXQuTGxtLlYxygIQUHJvbXB0a2l0XExsbVxWMeICHFByb21wdGtpdFxMbG1cVjFcR1BCTWV0YWRhdGHqAhJQcm9tcHRraXQ6OkxsbTo6VjFiBnByb3RvMw", [file_promptkit_common_v1_common]);

/**
 * @generated from message promptkit.llm.v1.LLMConfig
 */
export type LLMConfig = Message<"promptkit.llm.v1.LLMConfig"> & {
  /**
   * @generated from field: repeated promptkit.llm.v1.Tokenizer tokenizers = 1;
   */
  tokenizers: Tokenizer[];
};

/**
 * Describes the message promptkit.llm.v1.LLMConfig.
 * Use `create(LLMConfigSchema)` to create a new message.
 */
export const LLMConfigSchema: GenMessage<LLMConfig> = /*@__PURE__*/
  messageDesc(file_promptkit_llm_v1_llm, 0);

/**
 * @generated from message promptkit.llm.v1.Tokenizer
 */
export type Tokenizer = Message<"promptkit.llm.v1.Tokenizer"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: promptkit.llm.v1.Tokenizer.Type type = 2;
   */
  type: Tokenizer_Type;

  /**
   * @generated from oneof promptkit.llm.v1.Tokenizer.source
   */
  source: {
    /**
     * @generated from field: promptkit.common.v1.RemoteFile remote_file = 3;
     */
    value: RemoteFile;
    case: "remoteFile";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message promptkit.llm.v1.Tokenizer.
 * Use `create(TokenizerSchema)` to create a new message.
 */
export const TokenizerSchema: GenMessage<Tokenizer> = /*@__PURE__*/
  messageDesc(file_promptkit_llm_v1_llm, 1);

/**
 * @generated from enum promptkit.llm.v1.Tokenizer.Type
 */
export enum Tokenizer_Type {
  /**
   * @generated from enum value: TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: TYPE_SENTENCEPIECE = 1;
   */
  SENTENCEPIECE = 1,
}

/**
 * Describes the enum promptkit.llm.v1.Tokenizer.Type.
 */
export const Tokenizer_TypeSchema: GenEnum<Tokenizer_Type> = /*@__PURE__*/
  enumDesc(file_promptkit_llm_v1_llm, 1, 0);

