// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file promptkit/llm/v1/llm.proto (package promptkit.llm.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { RemoteFile } from "../../common/v1/common_pb.js";

/**
 * @generated from message promptkit.llm.v1.LLMConfig
 */
export class LLMConfig extends Message<LLMConfig> {
  /**
   * @generated from field: repeated promptkit.llm.v1.Tokenizer tokenizers = 1;
   */
  tokenizers: Tokenizer[] = [];

  constructor(data?: PartialMessage<LLMConfig>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "promptkit.llm.v1.LLMConfig";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "tokenizers", kind: "message", T: Tokenizer, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LLMConfig {
    return new LLMConfig().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LLMConfig {
    return new LLMConfig().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LLMConfig {
    return new LLMConfig().fromJsonString(jsonString, options);
  }

  static equals(a: LLMConfig | PlainMessage<LLMConfig> | undefined, b: LLMConfig | PlainMessage<LLMConfig> | undefined): boolean {
    return proto3.util.equals(LLMConfig, a, b);
  }
}

/**
 * @generated from message promptkit.llm.v1.Tokenizer
 */
export class Tokenizer extends Message<Tokenizer> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * @generated from field: promptkit.llm.v1.Tokenizer.Type type = 2;
   */
  type = Tokenizer_Type.UNSPECIFIED;

  /**
   * @generated from oneof promptkit.llm.v1.Tokenizer.source
   */
  source: {
    /**
     * @generated from field: promptkit.common.v1.RemoteFile remote_file = 3;
     */
    value: RemoteFile;
    case: "remoteFile";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<Tokenizer>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "promptkit.llm.v1.Tokenizer";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "type", kind: "enum", T: proto3.getEnumType(Tokenizer_Type) },
    { no: 3, name: "remote_file", kind: "message", T: RemoteFile, oneof: "source" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Tokenizer {
    return new Tokenizer().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Tokenizer {
    return new Tokenizer().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Tokenizer {
    return new Tokenizer().fromJsonString(jsonString, options);
  }

  static equals(a: Tokenizer | PlainMessage<Tokenizer> | undefined, b: Tokenizer | PlainMessage<Tokenizer> | undefined): boolean {
    return proto3.util.equals(Tokenizer, a, b);
  }
}

/**
 * @generated from enum promptkit.llm.v1.Tokenizer.Type
 */
export enum Tokenizer_Type {
  /**
   * @generated from enum value: TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: TYPE_SENTENCEPIECE = 1;
   */
  SENTENCEPIECE = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(Tokenizer_Type)
proto3.util.setEnumType(Tokenizer_Type, "promptkit.llm.v1.Tokenizer.Type", [
  { no: 0, name: "TYPE_UNSPECIFIED" },
  { no: 1, name: "TYPE_SENTENCEPIECE" },
]);

