from collections.abc import Callable, Sequence

class Pollable[T]:
    def subscribe(self) -> Pollable[None] | None: ...
    def release(self) -> None: ...
    def get(self) -> T: ...
    def wait(self) -> T: ...

class ArgIter:
    def read(self) -> tuple[bool, object | None, Pollable[None] | None]: ...

def monotonic() -> float: ...
def ready(poll: Sequence[tuple[Pollable[None], Pollable[object], object]]) -> bytes: ...
def drive(step: Callable[[], bool], suspend: bool = False) -> None: ...
def sleep(duration: float) -> Pollable[None]: ...
def emit(obj: object) -> None: ...
def hostcall(typ: str, obj: object) -> Pollable[object]: ...
