def debug(message: str, *args: object, **kwargs: object) -> None: ...
def info(message: str, *args: object, **kwargs: object) -> None: ...
def warning(message: str, *args: object, **kwargs: object) -> None: ...
def error(message: str, *args: object, **kwargs: object) -> None: ...
