// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file promptkit/common/v1/common.proto (package promptkit.common.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message promptkit.common.v1.RemoteFile
 */
export class RemoteFile extends Message<RemoteFile> {
  /**
   * @generated from field: string url = 1;
   */
  url = "";

  /**
   * The digest of the file "sha256:<hex>"
   *
   * @generated from field: string digest = 2;
   */
  digest = "";

  constructor(data?: PartialMessage<RemoteFile>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "promptkit.common.v1.RemoteFile";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "digest", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RemoteFile {
    return new RemoteFile().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RemoteFile {
    return new RemoteFile().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RemoteFile {
    return new RemoteFile().fromJsonString(jsonString, options);
  }

  static equals(a: RemoteFile | PlainMessage<RemoteFile> | undefined, b: RemoteFile | PlainMessage<RemoteFile> | undefined): boolean {
    return proto3.util.equals(RemoteFile, a, b);
  }
}

