// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file promptkit/common/v1/common.proto (package promptkit.common.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file promptkit/common/v1/common.proto.
 */
export const file_promptkit_common_v1_common: GenFile = /*@__PURE__*/
  fileDesc("CiBwcm9tcHRraXQvY29tbW9uL3YxL2NvbW1vbi5wcm90bxITcHJvbXB0a2l0LmNvbW1vbi52MSIpCgpSZW1vdGVGaWxlEgsKA3VybBgBIAEoCRIOCgZkaWdlc3QYAiABKAlClAEKF2NvbS5wcm9tcHRraXQuY29tbW9uLnYxQgtDb21tb25Qcm90b1ABogIDUENYqgITUHJvbXB0a2l0LkNvbW1vbi5WMcoCE1Byb21wdGtpdFxDb21tb25cVjHiAh9Qcm9tcHRraXRcQ29tbW9uXFYxXEdQQk1ldGFkYXRh6gIVUHJvbXB0a2l0OjpDb21tb246OlYxYgZwcm90bzM");

/**
 * @generated from message promptkit.common.v1.RemoteFile
 */
export type RemoteFile = Message<"promptkit.common.v1.RemoteFile"> & {
  /**
   * @generated from field: string url = 1;
   */
  url: string;

  /**
   * The digest of the file "sha256:<hex>"
   *
   * @generated from field: string digest = 2;
   */
  digest: string;
};

/**
 * Describes the message promptkit.common.v1.RemoteFile.
 * Use `create(RemoteFileSchema)` to create a new message.
 */
export const RemoteFileSchema: GenMessage<RemoteFile> = /*@__PURE__*/
  messageDesc(file_promptkit_common_v1_common, 0);

