#ifndef _PROMPTKIT_H_
#define _PROMPTKIT_H_

/* Don't modify this file manually. It is autogenerated by cbindgen. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum promptkit_error_code {
  PROMPTKIT_ERROR_CODE_OK = 0,
  PROMPTKIT_ERROR_CODE_INVALID_ARGUMENT = 1,
  PROMPTKIT_ERROR_CODE_INTERNAL = 2,
} promptkit_error_code;

typedef struct promptkit_context_handle promptkit_context_handle;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

enum promptkit_error_code promptkit_context_create(size_t nr_thread,
                                                   struct promptkit_context_handle **out_context);

enum promptkit_error_code promptkit_context_initialize(const struct promptkit_context_handle *ctx,
                                                       const char *path);

enum promptkit_error_code promptkit_context_config_set(const struct promptkit_context_handle *ctx,
                                                       const char *key,
                                                       const char *value);

void promptkit_context_destroy(struct promptkit_context_handle *_ctx);

const char *promptkit_last_error(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* _PROMPTKIT_H_ */
