package promptkit:python;

world python-vm {
    import http-client;

    import host: interface {
        emit: func(%data: string, %end: bool);
    }

    export vm : interface {
        variant error {
            python(string),
            unknown(string),
        }
        variant argument {
            json(string),
        }
        eval-script: func(%script: string) -> result<_, error>;
        call-func: func(%func: string, %args: list<argument>) -> result<_, error>;
    }
}